version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:
  data_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
      - data_volume:/data/
  frontend:
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/
  nginx:
    build: ./infra/
    env_file: .env
    ports:
      - 8021:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/