version: '3.3'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  frontend:
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/
  nginx:
    build: ./infra/
    env_file: .env
    ports:
      - "8021:80"
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/