# Generated by Django 3.2.16 on 2023-10-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
        ),
    ]
