# Generated by Django 3.2.16 on 2023-10-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231027_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Пользователь/рецепт', 'verbose_name_plural': 'Пользователи/рецепты'},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_pair',
        ),
    ]
