# Generated by Django 3.2.16 on 2023-11-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Рецепт/тэг', 'verbose_name_plural': 'Рецепты/тэги'},
        ),
    ]
