# Generated by Django 3.2.16 on 2023-10-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Любимый рецепт', 'verbose_name_plural': 'Любимые'},
        ),
    ]
