# Generated by Django 3.2.16 on 2023-11-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'В Списке покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
