# Generated by Django 3.2.16 on 2023-11-11 01:36

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Рецепт/тег', 'verbose_name_plural': 'Рецепты/теги'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(validators=[recipes.validators.time_validator], verbose_name='Количество'),
        ),
    ]
