# Generated by Django 3.2.16 on 2023-11-11 07:54

from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20231111_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(validators=[recipes.validators.amount_validator], verbose_name='Количество'),
        ),
    ]
